### ISSUE TITLE
build error when using with nextjs

### ISSUE THREAD

**Issue by ajitbohra** [sametweb/react-step-builder#42]
``` shell
> Build error occurred
/Users/ajitbohra/Documents/nextjs-webapp/node_modules/react-step-builder/src/dist/index.js:1
import React, { useContext, useEffect, useState } from "react";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:355:18)
    at wrapSafe (node:internal/modules/cjs/loader:1038:15)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.9979 (/Users/ajitbohra/Documents/nextjs-webapp/.next/server/pages/client-onboarding.js:188:51)
    at __webpack_require__ (/Users/ajitbohra/Documents/projects/nextjs-webapp/.next/server/webpack-runtime.js:25:42) {
  type: 'SyntaxError'
}
info  - Collecting page data .%
```

**Comment by sametweb** [comment]
I published a new beta version as a fix to this problem. Build command worked in my local repository for a NextJS application. Please try and let me know the results.

**Comment by ajitbohra** [comment]
Yes, it's working fine with the beta 👍

**Comment by Mairkur** [comment]
Hi, I got actually the same error. I use nextjs version ^11.0.1 and react-step-builder version ^2.0.10.

**Comment by sametweb** [comment]
> Hi, I got actually the same error. I use nextjs version ^11.0.1 and react-step-builder version ^2.0.10.

Please use 2.0.11 beta version. Everything is the same, Next.js problem is solved.

**Comment by Mairkur** [comment]
I didn't know where to find the number of this version thanks !
